"""empty message

Revision ID: 00004
Revises: 00003
Create Date: 2019-10-31 14:56:40.431394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00004'
down_revision = '00003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specification',
    sa.Column('specification_id', sa.Integer(), nullable=False),
    sa.Column('specification_name', sa.String(length=120), nullable=False),
    sa.Column('specification_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('specification_id'),
    sa.UniqueConstraint('specification_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specification')
    # ### end Alembic commands ###
