"""empty message

Revision ID: 00003
Revises: 00002
Create Date: 2019-10-31 14:49:54.770879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00003'
down_revision = '00002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement',
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['requirement_type.type_id'], name='fk_requirement_requirement_type'),
    sa.PrimaryKeyConstraint('requirement_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirement')
    # ### end Alembic commands ###
