"""empty message

Revision ID: 00002
Revises: 000001
Create Date: 2019-10-31 14:34:34.356643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00002'
down_revision = '000001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement_type',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('type_id'),
    sa.UniqueConstraint('type_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirement_type')
    # ### end Alembic commands ###
