"""empty message

Revision ID: 00005
Revises: 00004
Create Date: 2019-10-31 15:11:51.287491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00005'
down_revision = '00004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specification_requirement',
    sa.Column('specification_requirement_id', sa.Integer(), nullable=False),
    sa.Column('specification_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.requirement_id'], name='fk_requirement_specification_requirement_type'),
    sa.ForeignKeyConstraint(['specification_id'], ['specification.specification_id'], name='fk_specification_specification_requirement_type'),
    sa.PrimaryKeyConstraint('specification_requirement_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specification_requirement')
    # ### end Alembic commands ###
