"""empty message

Revision ID: 00008
Revises: 00007
Create Date: 2019-11-01 10:58:09.158139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00008'
down_revision = '00007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_task',
    sa.Column('session_task_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('requirement_type_answer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.requirement_id'], name='fk_requirement_session_task'),
    sa.ForeignKeyConstraint(['requirement_type_answer'], ['requirement_type.type_id'], name='fk_requirement_type_answer_session_task'),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], name='fk_session_session_task'),
    sa.PrimaryKeyConstraint('session_task_id')
    )
    op.add_column('session', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'completed')
    op.drop_table('session_task')
    # ### end Alembic commands ###
