"""empty message

Revision ID: 00006
Revises: 00005
Create Date: 2019-10-31 15:18:32.247008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00006'
down_revision = '00005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('score', sa.DECIMAL(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    # ### end Alembic commands ###
