"""empty message

Revision ID: 636c3fbbae94
Revises: 00010
Create Date: 2019-12-04 13:18:16.126671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00011'
down_revision = '00010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'end',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'end',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
