"""empty message

Revision ID: 5e147dd84b21
Revises: 00009
Create Date: 2019-12-04 12:52:19.130646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00010'
down_revision = '00009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('specification_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_session_specificatio', 'session', 'specification', ['specification_id'], ['specification_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_session_specificatio', 'session', type_='foreignkey')
    op.drop_column('session', 'specification_id')
    # ### end Alembic commands ###
